<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt"%>

<div class="row g-4">
  <div class="col-lg-5"><div class="card-soft p-3"><img class="w-100" style="height:560px;object-fit:cover;border-radius:10px;background:#f5f7f5" src="${pageContext.request.contextPath}/book-image?bookid=${book.bookid}&name=${book.coverImage}" alt="${book.title}"></div></div>
  <div class="col-lg-7"><div class="card-soft p-4 h-100"><div class="small text-muted-green mb-2">ISBN ${book.isbn}</div><h2 class="mb-3" style="color:#274f39;font-weight:800;">${book.title}</h2><div class="mb-2"><strong>Tác giả:</strong> ${book.authorNames}</div><div class="mb-2"><strong>Nhà xuất bản:</strong> ${book.publisher}</div><div class="mb-2"><strong>Ngày xuất bản:</strong> ${book.publishDate}</div><div class="mb-3"><strong>Tồn kho:</strong> <span class="${book.quantity == 0 ? 'text-danger' : 'text-success'}">${book.quantity} cuốn</span></div><div class="mb-3 book-price"><fmt:formatNumber value="${book.price}" type="number" groupingUsed="true"/> đ</div><p class="text-muted-green mb-4">${book.description}</p>
    <c:choose><c:when test="${book.quantity > 0 and not empty sessionScope.user}"><form action="${pageContext.request.contextPath}/cart/add" method="post" class="row g-2 align-items-end"><input type="hidden" name="bookid" value="${book.bookid}"><input type="hidden" name="redirect" value="/book/detail?bookid=${book.bookid}"><div class="col-sm-4"><label class="form-label">Số lượng</label><input class="form-control" type="number" name="quantity" value="1" min="1" max="${book.quantity}" required></div><div class="col-sm-8"><button class="btn-custom btn-custom-primary w-100" type="submit"><i class="bi bi-cart-plus"></i> Thêm vào giỏ hàng</button></div></form></c:when><c:when test="${book.quantity > 0}"><a class="btn-custom btn-custom-primary" href="${pageContext.request.contextPath}/login"><i class="bi bi-box-arrow-in-right"></i> Đăng nhập để mua hàng</a></c:when><c:otherwise><button class="btn-custom btn-custom-light" disabled>Hết hàng</button></c:otherwise></c:choose>
  </div></div>
</div>
<div class="card-soft p-4 mt-4" id="reviews"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0" style="color:#285b40;font-weight:800;">Đánh giá (${book.reviewCount})</h5></div><c:forEach var="r" items="${reviews}"><div class="py-3 border-bottom"><div class="d-flex justify-content-between"><strong>${r.reviewerName}</strong><span style="color:#d09a16"> <c:forEach begin="1" end="${r.rating}">★</c:forEach></span></div><div class="text-muted-green mt-1">${r.reviewText}</div></div></c:forEach><c:if test="${empty reviews}"><div class="text-muted-green">Chưa có đánh giá nào.</div></c:if><c:if test="${not empty sessionScope.user}"><form class="mt-4" action="${pageContext.request.contextPath}/book/review" method="post"><input type="hidden" name="bookid" value="${book.bookid}"><div class="row g-3"><div class="col-sm-3"><label class="form-label">Số sao</label><select name="rating" class="form-select"><option value="5">★★★★★</option><option value="4">★★★★</option><option value="3">★★★</option><option value="2">★★</option><option value="1">★</option></select></div><div class="col-sm-9"><label class="form-label">Nội dung</label><textarea name="review_text" class="form-control" rows="3" required></textarea></div></div><button class="btn-custom btn-custom-primary mt-3" type="submit">Gửi đánh giá</button></form></c:if></div>
